import { file_ } from '../../utils/file-util.js';
import { TABLE_REFS_FILENAME } from '../../constants.js';
import Path from 'path';
import { knexupUtil } from '../../utils/knexup-util.js';
import { _fn } from '../../utils/index.js';

const tokens = {
  do_not_edit__start: '/* AUTO-GENERATED BY knexup.js. ONLY MODIFY THE OBJECT KEYS/VALUES. */',
  export_const_tableRefs_equals: 'export const tableRefs = ',
  export_const__t_eq_tableRefs: 'export const tbl = tableRefs;'
};

export function buildTableRefsContent(source?: Record<string, string>) {
  const obj = _fn(() => {
    if (source) {
      return source;
    }
    return {};
  });

  return `${tokens.do_not_edit__start}
${tokens.export_const_tableRefs_equals}${printObj(obj)};

${tokens.export_const__t_eq_tableRefs}`;
}

export async function extractTableRefsObject() {
  const dir = await knexupUtil.getSchemaDirSegment();
  const tableRefsFile = Path.join(dir, TABLE_REFS_FILENAME);

  let contents = file_.readFile(tableRefsFile) || '';

  // Validate??

  contents = contents.trim()
    .replace(tokens.do_not_edit__start, '')
    .replace(tokens.export_const__t_eq_tableRefs, '')
    .replace(tokens.export_const_tableRefs_equals, '')
    .replace(/\s/g, '')
    .replace(/;+$/, '');

  return parseObjectString(contents);
}

function printObj(obj: Record<string, string>): string {
  let output = '{\n';

  for (let [k, v] of Object.entries(obj)) {
    output += `  ${k}: '${v}',\n`;
  }

  output = output.replace(/,+\s*$/, '');
  output += '\n}';

  return output;
}

function parseObjectString(s: string): Record<string, string> {
  const obj: any = {};

  // remove braces
  let _s = s.replace(/^\s*\{\s*/, '')
    .replace(/\s*}\s*$/, '');
  // console.log({ _s });

  // split by comma
  let entries = _s.split(/\s*,+\s*/);

  for (let entry of entries) {
    const pair = entry.split(/\s*:\s*/);

    const k = pair[0];
    const v = pair[1]?.replace(/'/g, '');
    if (k) {
      obj[k] = v;
    }
  }

  return obj;
}
